---
- name: Setup mysql
  hosts: db
  tasks:
    # - name: Install dependencies
    #   apt:
    # - name: Allow all hosts to connect
    #   shell:
    # - name: Start the mysql
    #   service:
    # - name: Create database
    #   mysql_db:
    # - name: Create database users
    #   mysql_user:
- name: Setup guestbook application
  hosts: web
  tasks:
    # - name: Install dependencies
    #   apt:
    # - name: Install flask
    #   pip:
    # - name: Download guestbook source code
    #   git:
    - name: Check if application is running
      shell: "ps -ef |grep -v grep | grep -w flask |awk '{print $2}'"
      register: process_id
      changed_when: process_id.stdout != ""
    - name: Stop the application
      shell: "kill {{ process_id.stdout }}"
      when: process_id.stdout != ""
    # - name: Start the application
    #   shell:
